spring:
  redis:
    port: 6379
    host: localhost

bucket4j:
  redis-url: redis://localhost:6379
  limits:
    GET:
      capacity: 10
      duration: 60
    POST:
      capacity: 5
      duration: 60