spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: order-service

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

logging:
  level:
    org.springframework.cloud.config.client: DEBUG